### ISSUE TITLE
Conflict between nokogiri-1.6.0 and nokogiri-1.8.0

### ISSUE THREAD

**Issue by ChrisPr1** [duritong/ruby-cobbler#10]
Ruby cobbler has a dependency on nokogiri 1.5.0, which is quite old at this point, and it conflicts with newer installations of nokogiri (1.8.0 in my case).

Can the dependency on nokogiri-1.5.0 simply be updated to a newer version, or does ruby-cobbler depend on deprecated features in 1.5.0

**Comment by ChrisPr1** [comment]
Excerpt from runtime error:

.../.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate cobbler-2.0.3, because nokogiri-1.8.0 conflicts with nokogiri (~> 1.5.0) (Gem::ConflictError)

**Comment by duritong** [comment]
The dependency came from ruby 1.8.7 (which is the system ruby for most cobbler installation platforms, I guess it still is, EL6), but it isn't necessary for newer ruby installation.

There might be away to trick the gemspec into the same behavior as the Gemfile, though I need to investigate.

But could you try the following patch to your installed gemspec?

https://github.com/duritong/ruby-cobbler/commit/9c176a7e1a222f2644bd65a2bb1fef3417508db6.patch

Knowing whether this fixes the problem would help a lot.

**Comment by ChrisPr1** [comment]
I patched the cobbler.gemspec but am not exactly sure what to do next. Do I need to 'rake gemspec'? the cobbler.gemspec file says not to modify that file directly in its header.

After patching cobbler.gemspec, I tried running a simple ruby script whose only cobbler reference was 'import cobbler' and I still get the same error:

<code>
/home/cprice/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate cobbler-2.0.3, because nokogiri-1.8.0 conflicts with nokogiri (~> 1.5.0) (Gem::ConflictError)
        from /home/cprice/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
        from /home/cprice/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems.rb:220:in `rescue in try_activate'
        from /home/cprice/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems.rb:213:in `try_activate'
        from /home/cprice/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /home/cprice/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
<code>
